version: "3.4"

x-defaults: &defaults
  restart: always

services:
  web:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/production/web/Dockerfile
    networks:
      - db
      - cache
    volumes:
      - .:/app
    depends_on:
      - db
      - cache
      - proxy

  db:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/base/db/Dockerfile
    networks:
      - db
    volumes:
      - production_db_data:/var/lib/db/data
      - production_db_backups:/backups
    env_file:
      - ./.envs/.production/.db
  
  cache:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/base/cache/Dockerfile
    networks:
      - cache
    env_file:
      - ./.envs/.production/.cache

  proxy:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/production/proxy/Dockerfile
    networks:
      - proxy
    depends_on:
      - app
    ports:
      - "80:80"

networks:
  db:
    driver: bridge
  cache:
    driver: bridge
  web:
    driver: bridge
  proxy:
    driver: bridge

volumes:
  production_db_data: { }
  production_db_backups: { }
